[package]
name = "telecon"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
teloxide = { version = "0.17.0", features = ["full"] }
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.10"
