[package]
name = "telecond"
version = "0.1.1"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
telecon = { path = "../telecon" }
teloxide = { version = "0.17.0", features = ["full"] }
anyhow = "1.0.100"
dirs = "6.0.0"
